# Aula 5 - Introdução às Bibliotecas Python e Numpy 🚀

## 🎯 Objetivos da Aula

Nesta aula, você aprenderá:
- Como instalar bibliotecas de terceiros
- Os básicos do Numpy 
- Pandas I
    - Carregar dados de xcls e csv para Pandas
    - Fatiar tabelas e plotar gráficos simples


## 🗂️ Estrutura da Aula
1. PiP
2. Numpy
4. Pandas
    1. DataFrame
    2. Series
    3. carregar dados do excel, csv...
    4. métodos e atributos de resumo
    (head, tail, describe, shape, dtypes,
    info...)
    5. métodos de fatiamento
    (loc, iloc, iat, at, T...)
    6. métodos gráficos
    (hist, plot, scatter)


## 📚 Material Complementar (Opcional)
1. 🔎 Pesquise sobre a biblioteca **Pandas** e **Numpy**.
2. 📖 Leia a documentação oficial.
3. ✏️ Entenda algum método ou função específica.
4. 💻 Replique com um código de teste.

🔗 [Documentação PiP](https://pip.pypa.io/en/stable/)

🔗 [Documentação Numpy](https://numpy.org/doc/stable/)

🔗 [Documentação Pandas](https://pandas.pydata.org/docs/user_guide/)

---

Como hoje iremos instalar código de terceiros em nosso jupyter é importante manter isso separado dentro de um ambiente virtual do python.

use "python3 -m venv .venv" para criar e "source .venv/bin/activate" para ativar.

Só então siga com o que faremos hoje, salvo se acompanha a aula por um google colab onde a sua sessão no documento já é um ambiente virtual privado na nuvem.

use no terminal ou em uma célula do notebook:
```bash
    pip install -q numpy pandas matplotlib openpyxl
```

In [2]:

pip install -q numpy pandas matplotlib openpyxl

Note: you may need to restart the kernel to use updated packages.


In [1]:
#rode se estiver num repositorio do git antes de mexer nesse arquivo
open('.gitignore', 'w').write('.gitignore\n.venv/\n__pycache__/\n.ipynb_checkpoints/\ndata/\noutputs/\n')

66

In [3]:
import numpy as np
import pandas as pd

# Exemplos práticos com Numpy

Vamos ver alguns exemplos simples que mostram o comportamento das principais funções do `numpy` usadas em ciência de dados.

In [4]:
# Criar arrays a partir de listas
a = np.array([1, 2, 3, 4])
print('array a:', a)


array a: [1 2 3 4]


In [5]:

# arange: intervalo com passo 1
b = np.arange(0, 10)
print('arange 0-9:', b)


arange 0-9: [0 1 2 3 4 5 6 7 8 9]


In [6]:

# zeros: array preenchido com zeros
z = np.zeros((2, 3))
print('zeros 2x3:', z)


zeros 2x3: [[0. 0. 0.]
 [0. 0. 0.]]


In [17]:

# linspace: 5 valores entre 0 e 1
l = np.linspace(0, 1, 5)
print('linspace 0-1:', l)


linspace 0-1: [0.   0.25 0.5  0.75 1.  ]


In [16]:

# random.rand: aleatórios em [0,1)
r = np.random.rand(5)
print('random:', r)


random: [0.6664352  0.61140036 0.2850163  0.51120774 0.66041241]


In [13]:

# reshape / flatten
m = np.arange(6).reshape(2, 3)
print('matriz m:\n', m)
print('m flatten:', m.flatten())

matriz m:
 [[0 1 2]
 [3 4 5]]
m flatten: [0 1 2 3 4 5]


In [18]:
l+r

array([0.6664352 , 0.86140036, 0.7850163 , 1.26120774, 1.66041241])

In [14]:
m*z

array([[0., 0., 0.],
       [0., 0., 0.]])

## carregamento de dados no pandas
em geral
``` python
pd.read_ 
```
Te retornando um DataFrame

In [ ]:
pd.read_excel
pd.read_csv

## DataFrame e Series
os dataframes do pandas são como tabelas do excel e series são séries, sequencias unidimencional de algo, geralmente representa uma coluna do dataframe.
 

In [19]:
#criando o primeiro dataframe
df = pd.DataFrame({'ar': [1,2,3], 'terra':[4,5,6]})
sr = pd.Series()

print(df, sr)

   ar  terra
0   1      4
1   2      5
2   3      6 Series([], dtype: object)


# Exemplos práticos com Pandas

Criaremos um pequeno `DataFrame` que simula populações de cidades e mostraremos as operações básicas de exploração e fatiamento vistas no roteiro.

In [30]:
# Tentar carregar o arquivo Excel definido na pasta
df_pop = pd.read_excel('pop.xlsx')
print('Arquivo carregado de:', "./pop.xlsx")


Arquivo carregado de: ./pop.xlsx


In [ ]:

# Visualização inicial
print('--- head() ---')
print(df_pop.head())

--- head() ---
    CD_MUN                      NM_MUN  POP_RESIDENTE  TX_CRESC  VAR_ABS
0  1100015  Alta Floresta D'Oeste - RO          21495     -1.05    -2897
1  1100023              Ariquemes - RO          96833      0.58     6480
2  1100031                 Cabixi - RO           5363     -1.35     -950
3  1100049                 Cacoal - RO          86895      0.84     8321
4  1100056             Cerejeiras - RO          15890     -0.58    -1139


In [31]:

# Visualização final
print('--- tail() ---')
print(df_pop.tail())

--- tail() ---
       CD_MUN               NM_MUN  POP_RESIDENTE  TX_CRESC  VAR_ABS
5565  5222005      Vianopolis - GO          14956      1.47     2408
5566  5222054  Vicentinopolis - GO           8768      1.45     1395
5567  5222203        Vila Boa - GO           4215     -0.96     -520
5568  5222302   Vila Propicio - GO           5815      1.03      670
5569  5300108        Brasilia - DF        2817068      0.76   244909


problema: temos um grande dataset da população de cidades do estado do Paraná e queremos poder o analisar.

vamos usar o pandas :panda emoji:!

In [ ]:
#Utilizamos o r para avisar ao python que / não representa uma sequência de escape
path_excel = r"Roteiros/Aula 5/pop.xlsx"