# Aula 5 - Introdução às Bibliotecas Python e Numpy 🚀

## 🎯 Objetivos da Aula

Nesta aula, você aprenderá:
- Como instalar bibliotecas de terceiros
- Os básicos do Numpy 
- Pandas I
    - Carregar dados de xcls e csv para Pandas
    - Fatiar tabelas e plotar gráficos simples


## 🗂️ Estrutura da Aula
1. PiP
2. Numpy
4. Pandas
    1. DataFrame
    2. Series
    3. carregar dados do excel, csv...
    4. métodos e atributos de resumo
    (head, tail, describe, shape, dtypes,
    info...)
    5. métodos de fatiamento
    (loc, iloc, iat, at, T...)
    6. métodos gráficos
    (hist, plot, scatter)


## 📚 Material Complementar (Opcional)
1. 🔎 Pesquise sobre a biblioteca **Pandas** e **Numpy**.
2. 📖 Leia a documentação oficial.
3. ✏️ Entenda algum método ou função específica.
4. 💻 Replique com um código de teste.

🔗 [Documentação PiP](https://pip.pypa.io/en/stable/)

🔗 [Documentação Numpy](https://numpy.org/doc/stable/)

🔗 [Documentação Pandas](https://pandas.pydata.org/docs/user_guide/)

---

Como hoje iremos instalar código de terceiros em nosso jupyter é importante manter isso separado dentro de um ambiente virtual do python.

use "python3 -m venv .venv" para criar e "source .venv/bin/activate" para ativar.

Só então siga com o que faremos hoje, salvo se acompanha a aula por um google colab onde a sua sessão no documento já é um ambiente virtual privado na nuvem.

use em uma célula do notebook:
```bash
    pip install -q numpy pandas matplotlib openpyxl
```

In [3]:

pip install -q numpy pandas matplotlib openpyxl

Note: you may need to restart the kernel to use updated packages.


In [4]:
#rode se estiver num repositorio do git antes de mexer nesse arquivo
open('.gitignore', 'w').write('.gitignore\n.venv/\n__pycache__/\n.ipynb_checkpoints/\ndata/\noutputs/\n')

66

In [5]:
import numpy as np
import pandas as pd

# Exemplos práticos com Numpy

Vamos ver alguns exemplos simples que mostram o comportamento das principais funções do `numpy` usadas em ciência de dados.

In [6]:
# Criar arrays a partir de listas
a = np.array([1, 2, 3, 4])
print('array a:', a)


array a: [1 2 3 4]


In [7]:

# arange: intervalo com passo 1
b = np.arange(0, 10)
print('arange 0-9:', b)


arange 0-9: [0 1 2 3 4 5 6 7 8 9]


In [8]:

# zeros: array preenchido com zeros
z = np.zeros((2, 3))
print('zeros 2x3:', z)


zeros 2x3: [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:

# linspace: 5 valores entre 0 e 1
l = np.linspace(0, 1, 5)
print('linspace 0-1:', l)


linspace 0-1: [0.   0.25 0.5  0.75 1.  ]


In [10]:

# random.rand: aleatórios em [0,1)
r = np.random.rand(5)
print('random:', r)


random: [0.98427592 0.5196348  0.34167861 0.82222973 0.08945195]


In [11]:

# reshape / flatten
m = np.arange(6).reshape(2, 3)
print('matriz m:\n', m)
print('m flatten:', m.flatten())

matriz m:
 [[0 1 2]
 [3 4 5]]
m flatten: [0 1 2 3 4 5]


In [12]:
l+r

array([0.98427592, 0.7696348 , 0.84167861, 1.57222973, 1.08945195])

In [13]:
m*z

array([[0., 0., 0.],
       [0., 0., 0.]])

## Carregamento de dados no pandas
em geral
``` python
pd.read_ 
```
Te retornando um DataFrame

In [14]:
pd.read_excel
pd.read_csv

<function pandas.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[HashableT, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[

## Entendendo DataFrame e Series


Um objeto do tipo ```Series``` no pandas é uma matriz unidimensional que contém dados de qualquer tipo, incluindo inteiros, flutuantes, strings, booleanos, objetos python etc. Um ```DataFrame``` é composto de muitas séries que funcionam como colunas. Ambos são objetos tabulares.

In [15]:
# Criando uma Series a partir de uma lista
temperaturas = pd.Series([30, 33, 40, 27, 18])
temperaturas

0    30
1    33
2    40
3    27
4    18
dtype: int64

In [16]:
# Alterando o índice de uma Series
temperaturas = pd.Series([30, 33, 40, 27, 18],
                         index = ["Seg", "Ter", "Qua", "Qui", "Sex"])
temperaturas

Seg    30
Ter    33
Qua    40
Qui    27
Sex    18
dtype: int64

In [17]:
# Acessando um valor da Series pelo índice
temperaturas["Qui"]

np.int64(27)

In [18]:
# Criando um DataFrame a partir de um dicionário
pessoas = pd.DataFrame({'Nome': ['Maria', 'João', 'Ana'],
                      'Idade': [25, 30, 22],
                      'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']})
pessoas

,Nome,Idade,Cidade
0,Maria,25,São Paulo
1,João,30,Rio de Janeiro
2,Ana,22,Belo Horizonte


In [19]:
# Acessando colunas de um DataFrame com um par de colchete --> formato Series
pessoas['Nome']

0    Maria
1     João
2      Ana
Name: Nome, dtype: str

In [20]:
# Acessando colunas de um DataFrame com dois pares de colchetes --> formato DataFrame
pessoas[['Nome']]

,Nome
0,Maria
1,João
2,Ana


In [21]:
# Acessando intervalos de linhas com colchetes
# pessoas[:1]
pessoas[1:3]

,Nome,Idade,Cidade
1,João,30,Rio de Janeiro
2,Ana,22,Belo Horizonte


# Exemplos práticos com Pandas
**pd.read_anything**

---

Vamos carregar um pequeno `DataFrame` das populações do Brasil, mostraremos as operações básicas de exploração e fatiamento.

In [22]:
# Tentar carregar o arquivo Excel definido na pasta
df_pop = pd.read_excel('pop.xlsx')
print('Arquivo carregado de:', "./pop.xlsx")


Arquivo carregado de: ./pop.xlsx


**Head e Tail**

---

Primeiramente é importante termos uma ideia geral de como devem ser as linhas de nossa tabela então usaremos os métodos HEAD e TAIL.

In [23]:
# Visualização inicial
print('--- head() ---')
print(df_pop.head(3))

--- head() ---
      CD_MUN                      NM_MUN POP_RESIDENTE  TX_CRESC  VAR_ABS
0  1100015.0  Alta Floresta D'Oeste - RO         21495     -1.05  -2897.0
1  1100023.0              Ariquemes - RO         96833      0.58   6480.0
2  1100031.0                 Cabixi - RO          5363     -1.35   -950.0


In [24]:
# Visualização final
print('--- tail() ---')
print(df_pop.tail(6))

--- tail() ---
         CD_MUN               NM_MUN POP_RESIDENTE  TX_CRESC   VAR_ABS
5578  5221908.0          Varjao - GO          3716      0.13      57.0
5579  5222005.0      Vianopolis - GO         14956      1.47    2408.0
5580  5222054.0  Vicentinopolis - GO          8768      1.45    1395.0
5581  5222203.0        Vila Boa - GO          4215     -0.96    -520.0
5582  5222302.0   Vila Propicio - GO          5815      1.03     670.0
5583  5300108.0        Brasilia - DF       2817068      0.76  244909.0


**Shape e DTypes**

---

Nosso DataFrame tem duas propriedades importantes que é shape e dtypes. Elas contam do formato de sua tabela e os typos de dados que cada coluna abriga respectivamente. 

In [25]:
# Conferindo as dimensões do DataFrame a partir do '.shape'
df_pop.shape


(5584, 5)

In [26]:
# Conferindo os tipos de dados no DataFrame a partir do '.dtypes'
df_pop.dtypes


CD_MUN           float64
NM_MUN               str
POP_RESIDENTE        str
TX_CRESC         float64
VAR_ABS          float64
dtype: object

tipos_tabela = {
    'CD_MUN'        :'int32',
    'NM_MUN'        :'str',
    'POP_RESIDENTE' :'int64',
    'TX_CRESC'      :'float64',
    'VAR_ABS'       :'int64'

}

In [28]:
# Conferindo os tipos de dados no DataFrame a partir do '.dtypes'
df_pop.dtypes


CD_MUN             int64
NM_MUN               str
POP_RESIDENTE      int64
TX_CRESC         float64
VAR_ABS            int64
dtype: object

In [29]:
# Conferindo um resumo geral de nosso DF com info
df_pop.info()


<class 'pandas.DataFrame'>
RangeIndex: 5584 entries, 0 to 5583
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   CD_MUN         5571 non-null   float64
 1   NM_MUN         5571 non-null   str    
 2   POP_RESIDENTE  5572 non-null   str    
 3   TX_CRESC       5571 non-null   float64
 4   VAR_ABS        5571 non-null   float64
dtypes: float64(3), str(2)
memory usage: 218.3 KB


Como queremos saber quantos valores nulos nossa tabela tem vamos usar .isnull que retornará uma nova tabela desta vez com valores booleanos (sim para null) e em seguida vamos somar cada coluna para conseguir uma medida que resume os números faltantes em cada coluna.

In [30]:
# Conferindo a quantidade de valores nulos no DataFrame a partir do '.isnull().sum()'
# df_pop.isnull()
df_pop.isnull().sum()


CD_MUN           13
NM_MUN           13
POP_RESIDENTE    12
TX_CRESC         13
VAR_ABS          13
dtype: int64

In [31]:
# Conferindo a quantidade de valores ausentes no DataFrame a partir do '.isna().sum()'
# df_pop.isna()
df_pop.isna().sum()


CD_MUN           13
NM_MUN           13
POP_RESIDENTE    12
TX_CRESC         13
VAR_ABS          13
dtype: int64

In [32]:
# Removendo valores nulos, usamos o inplace para afetar o DF diretamente e não uma cópia dele.
df_pop.dropna(inplace=True)


Ótimo os valores nulos não devem mais nos importunar!

In [33]:
# Preenchendo valores nulos
df_pop.fillna(0).isna().sum()


CD_MUN           0
NM_MUN           0
POP_RESIDENTE    0
TX_CRESC         0
VAR_ABS          0
dtype: int64

Vamos tentar novamente corrigir os tipos, agora que não temos valores nulos.

In [35]:
# Acessando o índice de um DataFrame
df_pop.index


RangeIndex(start=0, stop=5570, step=1)

In [36]:
# Análise descritiva de um DataFrame
df_pop.describe()


,CD_MUN,POP_RESIDENTE,TX_CRESC,VAR_ABS
count,5.571000e+03,5.571000e+03,5571.000000,5571.000000
mean,3.253007e+06,3.644992e+04,0.231343,2209.067133
std,9.857862e+05,2.064991e+05,1.074863,11896.937680
min,0.000000e+00,0.000000e+00,-4.890000,-257651.000000
25%,2.512089e+06,5.223000e+03,-0.400000,-349.500000
50%,3.146255e+06,1.106400e+04,0.130000,124.000000
75%,4.119177e+06,2.442650e+04,0.720000,1272.500000
max,5.300108e+06,1.145124e+07,9.230000,261533.000000


Note algo estranho em nossa descrição estátistica da tabela, o mínimo das populções é **zero**! Cidades não deveriam ser vazias, teremos que tirar as cidades sem habitantes do DF. Aproveitemos e conferimos que cidade que tem uma população que leva o máximo para 1.145124e+07!

**Filtrando valores**

---

Então antes de continuar teremos que aprender como fazer filtros boleanos para nossas tabelas

In [ ]:
#Filtremos nossa tabela pegando todas as cidades sem habitantes
Cidades_vazias = df_pop[df_pop['POP_RESIDENTE'] == 0]

# Tomamos apenas a lista de indices de nossa tabela temporária
indices = Cidades_vazias.index

# Usamos a função drop para remover as linhas referentes aos indices 
df_pop = df_pop.drop(indices)
df_pop.describe()

,CD_MUN,POP_RESIDENTE,TX_CRESC,VAR_ABS
count,5.570000e+03,5.570000e+03,5570.000000,5570.000000
mean,3.253591e+06,3.645647e+04,0.231384,2209.463734
std,9.849103e+05,2.065170e+05,1.074955,11897.968941
min,1.100015e+06,8.330000e+02,-4.890000,-257651.000000
25%,2.512126e+06,5.228000e+03,-0.400000,-349.750000
50%,3.146280e+06,1.106500e+04,0.130000,124.000000
75%,4.119190e+06,2.442725e+04,0.720000,1273.250000
max,5.300108e+06,1.145124e+07,9.230000,261533.000000


In [ ]:
# Desfazendo a configuração de uma coluna como index
df_pop = df_pop.reset_index()
df_pop.head(3)


,CD_MUN,NM_MUN,POP_RESIDENTE,TX_CRESC,VAR_ABS
0,1100015,Alta Floresta D'Oeste - RO,21495,-1.05,-2897
1,1100023,Ariquemes - RO,96833,0.58,6480
2,1100031,Cabixi - RO,5363,-1.35,-950


In [39]:
# Podemos usar .astype() para converter tipos de dados
df_pop[['TX_CRESC',	'VAR_ABS']] = df_pop[['TX_CRESC',	'VAR_ABS']].astype(str)
df_pop.dtypes


CD_MUN           int64
NM_MUN             str
POP_RESIDENTE    int64
TX_CRESC           str
VAR_ABS            str
dtype: object

In [40]:
# Renomendo colunas ou linhas
#df_pop = df_pop.rename(columns={'CD_MUN':'Código_municipal',	
#                                   'NM_MUN':'Nome_municipio',	
#                                   'POP_RESIDENTE':'população',	
#                                   'TX_CRESC':'taxa_de_crescimento',	
#                                   'VAR_ABS':'Variação_absoluta'})
df_pop = df_pop.rename(index={0: 'Zero', 1: 'Um'})
df_pop.head(3)


CD_MUN                      NM_MUN  POP_RESIDENTE TX_CRESC VAR_ABS
Zero  1100015  Alta Floresta D'Oeste - RO          21495    -1.05   -2897
Um    1100023              Ariquemes - RO          96833     0.58    6480
2     1100031                 Cabixi - RO           5363    -1.35    -950

In [41]:
# Removendo colunas ou linhas
# df_pop = df_pop.drop(columns=['Humidity'])
df_pop = df_pop.drop(index=['Zero', 'Um'])
df_pop.head(3)


,CD_MUN,NM_MUN,POP_RESIDENTE,TX_CRESC,VAR_ABS
2,1100031,Cabixi - RO,5363,-1.35,-950
3,1100049,Cacoal - RO,86895,0.84,8321
4,1100056,Cerejeiras - RO,15890,-0.58,-1139


In [ ]:
# Utilizando máscaras para filtrar dados em DataFrames
df_pop[df_pop['TX_CRESC'] > 3]
df_pop[df_pop['POP_RESIDENTE'] >100000]

TypeError: '>' not supported between instances of 'str' and 'float'

In [60]:
df_pop[df_pop['NM_MUN'] == 'Boa Vista - RR']

,CD_MUN,NM_MUN,POP_RESIDENTE,TX_CRESC,VAR_ABS
138,1400100,Boa Vista - RR,413486,3.17,129173


In [ ]:
# Temos que usar o tipo correto para conseguir filtrar com facilidade o que buscamos nas tabelas
df_pop[['TX_CRESC',	'VAR_ABS']] = df_pop[['TX_CRESC',	'VAR_ABS']].astype({'TX_CRESC':float, 'VAR_ABS':np.int64})

In [ ]:
df_pop[df_pop['Nome_municipio'] == 'Boa Vista - RR']

,Código_municipal,Nome_municipio,população,taxa_de_crescimento,Variação_absoluta
138,1400100,Boa Vista - RR,413486,3.17,129173
240,1505536,Parauapebas - PA,266424,4.68,112516
633,2111201,Sao Jose de Ribamar - MA,244579,3.50,82642
2061,2919553,Luis Eduardo Magalhaes - BA,107909,5.00,47804
2768,3145208,Nova Serrana - MG,105552,3.04,31853
3215,3302700,Marica - RJ,197300,3.71,69903
3241,3304524,Rio das Ostras - RJ,156491,3.33,50811
4020,4107652,Fazenda Rio Grande - PR,148873,5.13,67198
4362,4203204,Camboriu - SC,103074,4.28,40713
4436,4208203,Itajai - SC,264054,3.09,80681


**Colunas e indices**

---

Vamos ver um pouco como lidar com as propriedades de coluna e indice de nossa tabela.

In [524]:
# Acessando as colunas de um DataFrame
df_pop.columns


Index(['CD_MUN', 'NM_MUN', 'POP_RESIDENTE', 'TX_CRESC', 'VAR_ABS'], dtype='str')

In [ ]:
# Acessando o índice de um DataFrame
df_pop.index


Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       5574, 5575, 5576, 5577, 5578, 5579, 5580, 5581, 5582, 5583],
      dtype='int64', length=5571)

In [ ]:
# Configurando uma coluna do DataFrame como index
df_pop = df_pop.set_index('CD_MUN')
df_pop


,NM_MUN,POP_RESIDENTE,TX_CRESC,VAR_ABS
CD_MUN,,,,
1100015.0,Alta Floresta D'Oeste - RO,21495,-1.05,-2897.0
1100023.0,Ariquemes - RO,96833,0.58,6480.0
1100031.0,Cabixi - RO,5363,-1.35,-950.0
1100049.0,Cacoal - RO,86895,0.84,8321.0
1100056.0,Cerejeiras - RO,15890,-0.58,-1139.0
...,...,...,...,...
5222005.0,Vianopolis - GO,14956,1.47,2408.0
5222054.0,Vicentinopolis - GO,8768,1.45,1395.0
5222203.0,Vila Boa - GO,4215,-0.96,-520.0


In [ ]:
# Desfazendo a configuração de uma coluna como index
df_pop = df_pop.reset_index()
df_pop


,CD_MUN,NM_MUN,POP_RESIDENTE,TX_CRESC,VAR_ABS
0,1100015.0,Alta Floresta D'Oeste - RO,21495,-1.05,-2897.0
1,1100023.0,Ariquemes - RO,96833,0.58,6480.0
2,1100031.0,Cabixi - RO,5363,-1.35,-950.0
3,1100049.0,Cacoal - RO,86895,0.84,8321.0
4,1100056.0,Cerejeiras - RO,15890,-0.58,-1139.0
...,...,...,...,...,...
5566,5222005.0,Vianopolis - GO,14956,1.47,2408.0
5567,5222054.0,Vicentinopolis - GO,8768,1.45,1395.0
5568,5222203.0,Vila Boa - GO,4215,-0.96,-520.0
5569,5222302.0,Vila Propicio - GO,5815,1.03,670.0


In [525]:
# Renomendo colunas ou linhas
df_pop = df_pop.rename(columns={'CD_MUN':'Código_municipal',	
                                   'NM_MUN':'Nome_municipio',	
                                   'POP_RESIDENTE':'população',	
                                   'TX_CRESC':'taxa_de_crescimento',	
                                   'VAR_ABS':'Variação_absoluta'})
df_pop = df_pop.rename(index={0: 'Zero', 1: 'Um'})
df_pop.head(3)


,Código_municipal,Nome_municipio,população,taxa_de_crescimento,Variação_absoluta
Zero,1100015,Alta Floresta D'Oeste - RO,21495,-1.05,-2897
Um,1100023,Ariquemes - RO,96833,0.58,6480
2,1100031,Cabixi - RO,5363,-1.35,-950


In [526]:
# Removendo colunas ou linhas
# df_pop = df_pop.drop(columns=['Humidity'])
df_pop = df_pop.drop(index=['Zero', 'Um'])
df_pop.head(3)


,Código_municipal,Nome_municipio,população,taxa_de_crescimento,Variação_absoluta
2,1100031,Cabixi - RO,5363,-1.35,-950
3,1100049,Cacoal - RO,86895,0.84,8321
4,1100056,Cerejeiras - RO,15890,-0.58,-1139


In [527]:
df_pop[df_pop['Nome_municipio'] == 'Boa Vista - RR']

,Código_municipal,Nome_municipio,população,taxa_de_crescimento,Variação_absoluta
138,1400100,Boa Vista - RR,413486,3.17,129173
